services:
  # SQLite is used in memory, but we can also provide a PostgreSQL option
  postgres:
    image: docker.io/postgres:15-alpine
    pull_policy: missing
    environment:
      POSTGRES_DB: ees_test
      POSTGRES_USER: ees_test
      POSTGRES_PASSWORD: ees_test_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ees_test -d ees_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Ollama service for embeddings
  ollama:
    image: docker.io/ollama/ollama:0.3.14
    pull_policy: missing
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/version || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 60s
    restart: unless-stopped

  # Service to pull the required model
  ollama-setup:
    image: docker.io/ollama/ollama:0.3.14
    pull_policy: missing
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=ollama:11434
    volumes:
      - ollama_data:/root/.ollama
    command: >
      sh -c "
        echo 'Waiting for Ollama to be ready...' &&
        sleep 15 &&
        echo 'Pulling nomic-embed-text model...' &&
        for attempt in 1 2 3; do
          echo 'Pull attempt $$attempt of 3' &&
          if ollama pull nomic-embed-text; then
            echo 'Model pulled successfully!' &&
            break
          else
            echo 'Pull attempt $$attempt failed, retrying in 10 seconds...' &&
            sleep 10
          fi
        done
      "

  # Redis for caching (optional)
  redis:
    image: docker.io/redis:7-alpine
    pull_policy: missing
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_test_data:
  ollama_data: