/**
 * Environment variable keys for provider configuration
 * Centralized constants to avoid circular dependencies
 */

export const ENV_KEYS = {
  // Default provider
  DEFAULT_PROVIDER: "EES_DEFAULT_PROVIDER",

  // Ollama configuration
  OLLAMA_BASE_URL: "EES_OLLAMA_BASE_URL",
  OLLAMA_DEFAULT_MODEL: "EES_OLLAMA_DEFAULT_MODEL",

  // OpenAI configuration
  OPENAI_API_KEY: "EES_OPENAI_API_KEY",
  OPENAI_BASE_URL: "EES_OPENAI_BASE_URL",
  OPENAI_DEFAULT_MODEL: "EES_OPENAI_DEFAULT_MODEL",
  OPENAI_ORGANIZATION: "EES_OPENAI_ORGANIZATION",

  // Google AI configuration
  GOOGLE_API_KEY: "EES_GOOGLE_API_KEY",
  GOOGLE_BASE_URL: "EES_GOOGLE_BASE_URL",
  GOOGLE_DEFAULT_MODEL: "EES_GOOGLE_DEFAULT_MODEL",

  // Azure OpenAI configuration
  AZURE_API_KEY: "EES_AZURE_API_KEY",
  AZURE_BASE_URL: "EES_AZURE_BASE_URL",
  AZURE_API_VERSION: "EES_AZURE_API_VERSION",
  AZURE_DEFAULT_MODEL: "EES_AZURE_DEFAULT_MODEL",

  // Cohere configuration
  COHERE_API_KEY: "EES_COHERE_API_KEY",
  COHERE_BASE_URL: "EES_COHERE_BASE_URL",
  COHERE_DEFAULT_MODEL: "EES_COHERE_DEFAULT_MODEL",

  // Mistral configuration
  MISTRAL_API_KEY: "EES_MISTRAL_API_KEY",
  MISTRAL_BASE_URL: "EES_MISTRAL_BASE_URL",
  MISTRAL_DEFAULT_MODEL: "EES_MISTRAL_DEFAULT_MODEL",

  // Rate limiting configuration
  RATE_LIMIT_ENABLED: "EES_RATE_LIMIT_ENABLED",
  RATE_LIMIT_WINDOW_MS: "EES_RATE_LIMIT_WINDOW_MS",
  RATE_LIMIT_GENERAL: "EES_RATE_LIMIT_GENERAL",
  RATE_LIMIT_EMBEDDING: "EES_RATE_LIMIT_EMBEDDING",
  RATE_LIMIT_SEARCH: "EES_RATE_LIMIT_SEARCH",
  RATE_LIMIT_READ: "EES_RATE_LIMIT_READ",
} as const